-- Generated by tools/render_tracker_logic.py; edit randomizer_logic.json.
function has(item)
  return Tracker:ProviderCountForCode(item) > 0
end

function ACCESS_W1_1()
  return (has("access_w1_1") or true)
end

function ACCESS_W1_2()
  return (has("access_w1_2") or has("star_w1_1"))
end

function ACCESS_W1_3()
  return (has("access_w1_3") or has("star_w1_2"))
end

function ACCESS_W1_4()
  return (has("access_w1_4") or has("star_w1_3"))
end

function ACCESS_W1_5()
  return (has("access_w1_5") or has("star_w1_3_alt"))
end

function ACCESS_W1_6()
  return (has("access_w1_6") or has("star_w1_4") or has("star_w1_5"))
end

function ACCESS_W2_1()
  return (has("access_w2_1"))
end

function ACCESS_W2_2()
  return (has("access_w2_2") or has("star_w2_1"))
end

function ACCESS_W2_3()
  return (has("access_w2_3") or has("star_w2_2"))
end

function ACCESS_W2_4()
  return (has("access_w2_4") or has("star_w2_3_alt"))
end

function ACCESS_W2_5()
  return (has("access_w2_5") or has("star_w2_3"))
end

function ACCESS_W3_1()
  return (has("access_w3_1") or true)
end

function ACCESS_W3_10()
  return (has("access_w3_10") or has("star_w3_9"))
end

function ACCESS_W3_11()
  return (has("access_w3_11") or has("star_w3_4_alt"))
end

function ACCESS_W3_12()
  return (has("access_w3_12") or has("star_w3_11"))
end

function ACCESS_W3_2()
  return (has("access_w3_2") or has("star_w3_1"))
end

function ACCESS_W3_3()
  return (has("access_w3_3") or has("star_w3_2"))
end

function ACCESS_W3_4()
  return (has("access_w3_4") or has("star_w3_3"))
end

function ACCESS_W3_5()
  return (has("access_w3_5") or has("star_w3_4"))
end

function ACCESS_W3_6()
  return (has("access_w3_6") or has("star_w3_5"))
end

function ACCESS_W3_7()
  return (has("access_w3_7") or has("star_w3_3_left") or has("star_w3_10"))
end

function ACCESS_W3_8()
  return (has("access_w3_8") or has("star_w3_7"))
end

function ACCESS_W3_9()
  return (has("access_w3_9") or has("star_w3_3_middle") or has("star_w3_11_alt"))
end

function ACCESS_W4_1()
  return (has("access_w4_1"))
end

function ACCESS_W4_2()
  return (has("access_w4_2") or has("star_w4_1"))
end

function ACCESS_W4_3()
  return (has("access_w4_3") or has("star_w4_2"))
end

function ACCESS_W4_4()
  return (has("access_w4_4") or has("star_w4_3"))
end

function ACCESS_W4_5()
  return (has("access_w4_5") or has("star_w4_1_alt"))
end

function ACCESS_W4_6()
  return (has("access_w4_6") or has("star_w4_5"))
end

function ACCESS_W5_1()
  return (has("access_w5_1"))
end

function ACCESS_W5_2()
  return (has("access_w5_2") or has("star_w5_1"))
end

function ACCESS_W5_3()
  return (has("access_w5_3") or has("star_w5_2"))
end

function ACCESS_W5_4()
  return (has("access_w5_4") or has("star_w5_3"))
end

function ACCESS_W5_5()
  return (has("access_w5_5") or has("star_w5_4"))
end

function ACCESS_W5_6()
  return (has("access_w5_6") or has("star_w5_5"))
end

function ACCESS_W6_1()
  return (has("access_w6_1"))
end

function ACCESS_W6_2()
  return (has("access_w6_2") or (has("royal_w1") and has("royal_w2") and has("royal_w3") and has("royal_w4") and has("royal_w5") and has("paperization") and has("scrap_hidden_bowser_castle")))
end

function ACCESS_W6_3()
  return (has("access_w6_3") or has("star_w6_2"))
end

function W1_BRIDGE()
  return (has("paperization") and has("scrap_wooden_bridge"))
end

function W1_SECRET()
  return (has("paperization") and has("sticker_secret_door") and has("door_place_w1_2"))
end

function W1_PIPE()
  return (has("paperization") and has("scrap_green_warp_pipe"))
end

function W1_GATE()
  return (has("paperization") and has("scrap_white_gate"))
end

function W1_FORTRESS()
  return (has("paperization") and has("scrap_block_switch") and has("boss_unlock_w1"))
end

function W2_TABLET()
  return (has("paperization") and has("scrap_tablet_piece_1") and has("scrap_tablet_piece_2") and has("scrap_tablet_piece_3"))
end

function W2_BOSS()
  return (has("paperization") and has("scrap_tablet_piece_1") and has("scrap_tablet_piece_2") and has("scrap_tablet_piece_3") and has("boss_unlock_w2"))
end

function W3_BRIDGE()
  return (has("paperization") and has("scrap_bridge_part_1") and has("scrap_bridge_part_2") and has("scrap_bridge_part_3"))
end

function W4_BOO()
  return (has("req_book_of_sealing"))
end

function ALL_ROYALS()
  return (has("royal_w1") and has("royal_w2") and has("royal_w3") and has("royal_w4") and has("royal_w5"))
end

function W6_FINAL()
  return (has("boss_unlock_w6"))
end

