"""Render PopTracker Lua from the same predicates used by logic tests."""

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]


def expression(rule: dict[str, Any]) -> str:
    if "item" in rule:
        return "has(" + json.dumps(rule["item"]) + ")"
    key = next(iter(rule))
    if key not in ("all", "any"):
        raise ValueError(f"Unsupported tracker predicate: {rule}")
    terms = [expression(child) for child in rule[key]]
    if not terms:
        return "true" if key == "all" else "false"
    return "(" + (" and " if key == "all" else " or ").join(terms) + ")"


def render(model: dict[str, dict[str, Any]]) -> str:
    lua = (
        "-- Generated by tools/render_tracker_logic.py; "
        "edit randomizer_logic.json.\n"
    )
    lua += (
        "function has(item)\n"
        "  return Tracker:ProviderCountForCode(item) > 0\nend\n\n"
    )
    for name, rule in model.items():
        lua += f"function {name}()\n  return {expression(rule)}\nend\n\n"
    return lua


if __name__ == "__main__":
    model = json.loads((ROOT / "scripts/randomizer_logic.json").read_text())
    (ROOT / "scripts/logic.lua").write_text(render(model), encoding="utf-8")
